openapi: 3.0.0
info:
  title: Portfolio Management System - Portfolios API
  version: 1.2.1
  description: |
    RESTful API for managing investment portfolios.
    
    Includes performance metrics, asset allocation, and holdings management.
  contact:
    name: API Support
    email: support@portfoliomgmt.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://portfolio-mgmt-system-997b2c07833c.herokuapp.com/api/v1
    description: Production server
  - url: http://localhost:3001/api/v1
    description: Development server

tags:
  - name: Portfolios
    description: Portfolio management endpoints

paths:
  /portfolios:
    get:
      summary: List all portfolios
      description: Retrieve a list of all portfolios across all accounts
      operationId: getPortfolios
      tags:
        - Portfolios
      parameters:
        - name: parameter
          in: query
          required: false
          description: Optional query parameter
          schema:
            type: string
      responses:
        '200':
          description: List of portfolios
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Portfolio'
                  timestamp:
                    type: string
                    format: date-time

    post:
      summary: Create a new portfolio
      description: Create a new portfolio within an account
      operationId: createPortfolio
      tags:
        - Portfolios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PortfolioCreate'
      responses:
        '201':
          description: Portfolio created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/Portfolio'

  /portfolios/{portfolioId}:
    get:
      summary: Get portfolio by ID
      description: Retrieve detailed information about a specific portfolio
      operationId: getPortfolioById
      tags:
        - Portfolios
      parameters:
        - $ref: '#/components/parameters/portfolioId'
      responses:
        '200':
          description: Portfolio details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/Portfolio'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update a portfolio
      description: Update an existing portfolio's details
      operationId: updatePortfolio
      tags:
        - Portfolios
      parameters:
        - $ref: '#/components/parameters/portfolioId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PortfolioUpdate'
      responses:
        '200':
          description: Portfolio updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/Portfolio'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a portfolio
      description: Remove a portfolio and all related holdings and transactions
      operationId: deletePortfolio
      tags:
        - Portfolios
      parameters:
        - $ref: '#/components/parameters/portfolioId'
      responses:
        '200':
          description: Portfolio deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/Portfolio'
        '404':
          $ref: '#/components/responses/NotFound'

  /portfolios/{portfolioId}/performance:
    get:
      summary: Get portfolio performance metrics
      description: |
        Retrieve comprehensive performance data including:
        - Total market value and cost basis
        - Unrealized gain/loss
        - Asset and sector allocation
        - Top holdings
      operationId: getPortfolioPerformance
      tags:
        - Portfolios
      parameters:
        - $ref: '#/components/parameters/portfolioId'
      responses:
        '200':
          description: Portfolio performance data
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/PortfolioPerformance'
        '404':
          $ref: '#/components/responses/NotFound'

  /portfolios/account/{accountId}:
    get:
      summary: Get portfolios for an account
      description: Retrieve all portfolios within a specific account
      operationId: getPortfoliosByAccount
      tags:
        - Portfolios
      parameters:
        - name: accountId
          in: path
          required: true
          description: The account ID
          schema:
            type: string
          example: ACC-001
      responses:
        '200':
          description: List of portfolios in the account
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Portfolio'

components:
  parameters:
    portfolioId:
      name: portfolioId
      in: path
      required: true
      description: Unique identifier for the portfolio
      schema:
        type: string
      example: PRT-001

  schemas:
    Portfolio:
      type: object
      properties:
        portfolioId:
          type: string
          example: PRT-001
        accountId:
          type: string
          example: ACC-001
        clientId:
          type: string
          example: CLI-001
        portfolioName:
          type: string
          example: Growth Portfolio
        portfolioType:
          type: string
          enum: [MANAGED, SELF_DIRECTED]
          example: MANAGED
        modelPortfolio:
          type: string
          example: GROWTH_60_40
        inceptionDate:
          type: string
          format: date
          example: "2020-06-20"
        benchmarkIndex:
          type: string
          example: SPY
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    PortfolioCreate:
      type: object
      required:
        - accountId
        - clientId
        - portfolioName
      properties:
        accountId:
          type: string
          example: ACC-001
        clientId:
          type: string
          example: CLI-001
        portfolioName:
          type: string
          example: New Growth Portfolio
        portfolioType:
          type: string
          enum: [MANAGED, SELF_DIRECTED]
          example: MANAGED
        modelPortfolio:
          type: string
          example: GROWTH_60_40
        inceptionDate:
          type: string
          format: date
          example: "2024-01-15"
        benchmarkIndex:
          type: string
          example: SPY

    PortfolioUpdate:
      type: object
      properties:
        portfolioName:
          type: string
        portfolioType:
          type: string
          enum: [MANAGED, SELF_DIRECTED]
        modelPortfolio:
          type: string
        benchmarkIndex:
          type: string

    PortfolioPerformance:
      type: object
      properties:
        portfolio:
          $ref: '#/components/schemas/Portfolio'
        performance:
          type: object
          properties:
            totalMarketValue:
              type: number
              example: 115000.00
            totalCostBasis:
              type: number
              example: 100000.00
            totalUnrealizedGain:
              type: number
              example: 15000.00
            totalUnrealizedGainPercent:
              type: number
              example: 15.00
            dayChange:
              type: number
              example: 450.00
            dayChangePercent:
              type: number
              example: 0.39
            assetAllocation:
              type: object
              example:
                STOCK: 70.0
                BOND: 15.0
                ETF: 15.0
            sectorAllocation:
              type: object
              example:
                TECHNOLOGY: 35.0
                HEALTHCARE: 15.0
                FINANCIAL: 12.0
            topHoldings:
              type: array
              items:
                type: object
                properties:
                  symbol:
                    type: string
                  weight:
                    type: number

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
              example: NOT_FOUND
            message:
              type: string
              example: Portfolio not found
        timestamp:
          type: string
          format: date-time

  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

